//elementos, mapeamentos das páginas web

export const ELEMENTS = {
    botãoLandingPage: 'a.btn-default',
    campoNome: '#nome',
    campoSenha: '#senha',
    campoEmail: '#email',
    campoConfirmarSenha: '#confirmarSenha',
    botãoCadastrar: '#btn-cadastro',
    logoPaginaPrincipal: '.fs-2',
    botãoLogin: '#btn-login',
    botãoRegistrarse: '.spanNoAccount > strong > .text-primary',
    esqueciMinhaSenha: '.forgotpassword > span > strong > .text-primary',
    barraPesquisa: '#search-input',
    botãoPesquisar: '.col-sm-auto > .btn',
    bolsaDoCafé: '.d-flex > .btn',
    assento12: '.row--4 > .seats > :nth-child(1) > label',
    assento13: '.row--4 > .seats > :nth-child(2) > label',
    nomePassageiro12: '#nome-12',
    emailPassageiro12: '#email-12',
    telefonePassageiro12: '#telefone-12',
    cpfPassageiro12: '#cpf-12',
    nomePassageiro13: '#nome-13',
    emailPassageiro13: '#email-13',
    telefonePassageiro13: '#telefone-13',
    cpfPassageiro13: '#cpf-13',
    botãoReservaAssento: '#btnPagamento',
    botãoCredito: '#card-credit',
    botãoDebito: '#card-debit',
    nomeTitularCartão: '#cardholder',
    numeroCartão: '#cardnumber',
    validadeCartão: '#validate',
    cvvCartão: '#cvv',
    parcelasLista: '#installments',
    botãoComprar: '#btnComprar',
    historicoPedidos: '.btn-success',
    continuarComprando: '.btn-outline-secondary',
    detalhesExcursão: '.detalhes',
    fecharJanelaDetalhes: '.close-button',
    logout: '#logout'
}